!  NOTE:	*** USE KRTSYS.COM TO BUILD KM ON RT-11 V5 SYSTEMS ***
!  27-Sep-97	BUILD KM ON RT-11 V4 SYSTEMS AND TSX V5 SYSTEMS ONLY
!		KRT will only run under RT-11FB if V4, or use KRTMIN
MAC/OBJ:KM KRTSJ.CND+KRTKM
LINK/EXE:KM.SYS KM
MAC/OBJ:KMTSX KRTTSX.CND+KRTKM
LINK/EXE:KM.TSX KMTSX
DEL/NOQ KM*.OBJ
