!  NOTE:	*** USE KRTSV4.COM TO BUILD KM ON RT-11 V4 SYSTEMS ***
!  27-Sep-97	Build KM under RT-11 V5 and above, and TSX-Plus V6 and above
MAC/OBJ:KM KRTSJ.CND+KRTKM
LINK/NOBIT/EXE:KM.SYS KM
MAC/OBJ:KMX KRTXM.CND+KRTKM
LINK/NOBIT/EXE:KMX.SYS KMX
MAC/OBJ:KMTSX KRTTSX.CND+KRTKM
LINK/NOBIT/EXE:KM.TSX KMTSX
DEL/NOQ KM*.OBJ
